apiVersion: apps/v1
kind: Deployment
metadata:
 name: ecomm-deployment
 labels:
  app: ecomm
spec:
 replicas: 2
 selector:
 matchLabels:
  app: ecomm
 template:
  metadata:
   name: ecomm-pod
   labels:
    app: ecomm
  spec:
   containers:
   - name: ecomm-container
     image: devopsproject2.azurecr.io/e-comm:latest
     ports:
      - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
 name: ecomm-svc
spec:
 type: LoadBalancer
 ports:
  - targetPort: 8080
    port: 8080
 selector:
  app: ecomm